# Generated by Django 5.1.7 on 2025-03-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Memeseum_app', '0005_alter_meme_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='imagem',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
