# Generated by Django 5.1.7 on 2025-03-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Memeseum_app', '0007_alter_meme_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='ano',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meme',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meme',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
